### ISSUE TITLE
Error: %b requires a bytes-like object, or an object that implements __bytes__, not 'NoneType'

### ISSUE THREAD

**Issue by ogry** [expenses/GAPDownloader#17]
Consistent with any url and any zoom level.

**Comment by lovasoa** [comment]
Hello,
  I cannot reproduce this issue. Can you give more information, such as the version of python you use, the exact command-line you use to invoke the script, and the full stack trace you receive ?

**Comment by lovasoa** [comment]
There isn't a single instance of `%b` in this script...

**Comment by ogry** [comment]
```
C:\Python\gapdecoder-master>py tile_fetch.py
Enter the url of the image: https://artsandculture.google.com/asset/waterloo-bridge-claude-monet/DwE25c4VOCwboQ
Downloading image meta-information...
waterloo-bridge-claude-monet - zoom levels:
level  0:    500 x    398 (     1 tiles)
level  1:   1000 x    796 (     4 tiles)
level  2:   2000 x   1592 (    16 tiles)
level  3:   4000 x   3185 (    56 tiles)
Which level do you want to download? 0
Downloading tiles...
Traceback (most recent call last):
  File "tile_fetch.py", line 181, in <module>
    main()
  File "tile_fetch.py", line 177, in main
    loop.run_until_complete(coro)
  File "C:\Python\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "tile_fetch.py", line 131, in load_tiles
    tiles = await async_tile_fetcher.gather_progress(awaitable_tiles)
  File "C:\Python\gapdecoder-master\async_tile_fetcher.py", line 44, in gather_progress
    for i, a in enumerate(awaitables)
  File "C:\Python\gapdecoder-master\async_tile_fetcher.py", line 36, in print_percent
    res = await awaitable
  File "tile_fetch.py", line 100, in fetch_tile
    image_url = image_info.url(x, y, z)
  File "tile_fetch.py", line 64, in url
    return compute_url(self.path, self.token, x, y, z)
  File "tile_fetch.py", line 32, in compute_url
    sign_path = b'%s=x%d-y%d-z%d-t%s' % (path, x, y, z, token)
TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'NoneType'

```

Python version 3.7.5

```
C:\Python\gapdecoder-master>py -v
import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
# installing zipimport hook
import 'zipimport' # <class '_frozen_importlib.BuiltinImporter'>
# installed zipimport hook
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'nt' # <class '_frozen_importlib.BuiltinImporter'>
import _thread # previously loaded ('_thread')
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import _weakref # previously loaded ('_weakref')
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import 'winreg' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Python\lib\encodings\__pycache__\__init__.cpython-37.pyc matches C:\Python\lib\encodings\__init__.py
# code object from 'C:\\Python\\lib\\encodings\\__pycache__\\__init__.cpython-37.pyc'
# C:\Python\lib\__pycache__\codecs.cpython-37.pyc matches C:\Python\lib\codecs.py
# code object from 'C:\\Python\\lib\\__pycache__\\codecs.cpython-37.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA5B3F48>
# C:\Python\lib\encodings\__pycache__\aliases.cpython-37.pyc matches C:\Python\lib\encodings\aliases.py
# code object from 'C:\\Python\\lib\\encodings\\__pycache__\\aliases.cpython-37.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA740C88>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA5AEF08>
# C:\Python\lib\encodings\__pycache__\utf_8.cpython-37.pyc matches C:\Python\lib\encodings\utf_8.py
# code object from 'C:\\Python\\lib\\encodings\\__pycache__\\utf_8.cpython-37.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA752FC8>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Python\lib\encodings\__pycache__\latin_1.cpython-37.pyc matches C:\Python\lib\encodings\latin_1.py
# code object from 'C:\\Python\\lib\\encodings\\__pycache__\\latin_1.cpython-37.pyc'
import 'encodings.latin_1' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA753888>
# C:\Python\lib\__pycache__\io.cpython-37.pyc matches C:\Python\lib\io.py
# code object from 'C:\\Python\\lib\\__pycache__\\io.cpython-37.pyc'
# C:\Python\lib\__pycache__\abc.cpython-37.pyc matches C:\Python\lib\abc.py
# code object from 'C:\\Python\\lib\\__pycache__\\abc.cpython-37.pyc'
import '_abc' # <class '_frozen_importlib.BuiltinImporter'>
import 'abc' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA758408>
import 'io' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA753908>
# C:\Python\lib\__pycache__\site.cpython-37.pyc matches C:\Python\lib\site.py
# code object from 'C:\\Python\\lib\\__pycache__\\site.cpython-37.pyc'
# C:\Python\lib\__pycache__\os.cpython-37.pyc matches C:\Python\lib\os.py
# code object from 'C:\\Python\\lib\\__pycache__\\os.cpython-37.pyc'
# C:\Python\lib\__pycache__\stat.cpython-37.pyc matches C:\Python\lib\stat.py
# code object from 'C:\\Python\\lib\\__pycache__\\stat.cpython-37.pyc'
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA777788>
# C:\Python\lib\__pycache__\ntpath.cpython-37.pyc matches C:\Python\lib\ntpath.py
# code object from 'C:\\Python\\lib\\__pycache__\\ntpath.cpython-37.pyc'
# C:\Python\lib\__pycache__\genericpath.cpython-37.pyc matches C:\Python\lib\genericpath.py
# code object from 'C:\\Python\\lib\\__pycache__\\genericpath.cpython-37.pyc'
import 'genericpath' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA7817C8>
import 'ntpath' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA77A248>
# C:\Python\lib\__pycache__\_collections_abc.cpython-37.pyc matches C:\Python\lib\_collections_abc.py
# code object from 'C:\\Python\\lib\\__pycache__\\_collections_abc.cpython-37.pyc'
import '_collections_abc' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA787388>
import 'os' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA767788>
# C:\Python\lib\__pycache__\_sitebuiltins.cpython-37.pyc matches C:\Python\lib\_sitebuiltins.py
# code object from 'C:\\Python\\lib\\__pycache__\\_sitebuiltins.cpython-37.pyc'
import '_sitebuiltins' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA767D48>
# C:\Python\lib\__pycache__\_bootlocale.cpython-37.pyc matches C:\Python\lib\_bootlocale.py
# code object from 'C:\\Python\\lib\\__pycache__\\_bootlocale.cpython-37.pyc'
import '_locale' # <class '_frozen_importlib.BuiltinImporter'>
import '_bootlocale' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA770FC8>
# C:\Python\lib\encodings\__pycache__\cp1252.cpython-37.pyc matches C:\Python\lib\encodings\cp1252.py
# code object from 'C:\\Python\\lib\\encodings\\__pycache__\\cp1252.cpython-37.pyc'
import 'encodings.cp1252' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA7750C8>
# C:\Python\lib\__pycache__\types.cpython-37.pyc matches C:\Python\lib\types.py
# code object from 'C:\\Python\\lib\\__pycache__\\types.cpython-37.pyc'
import 'types' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA8E3688>
# C:\Python\lib\importlib\__pycache__\__init__.cpython-37.pyc matches C:\Python\lib\importlib\__init__.py
# code object from 'C:\\Python\\lib\\importlib\\__pycache__\\__init__.cpython-37.pyc'
# C:\Python\lib\__pycache__\warnings.cpython-37.pyc matches C:\Python\lib\warnings.py
# code object from 'C:\\Python\\lib\\__pycache__\\warnings.cpython-37.pyc'
import 'warnings' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA8E40C8>
import 'importlib' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA8DC788>
# C:\Python\lib\importlib\__pycache__\util.cpython-37.pyc matches C:\Python\lib\importlib\util.py
# code object from 'C:\\Python\\lib\\importlib\\__pycache__\\util.cpython-37.pyc'
# C:\Python\lib\importlib\__pycache__\abc.cpython-37.pyc matches C:\Python\lib\importlib\abc.py
# code object from 'C:\\Python\\lib\\importlib\\__pycache__\\abc.cpython-37.pyc'
# C:\Python\lib\importlib\__pycache__\machinery.cpython-37.pyc matches C:\Python\lib\importlib\machinery.py
# code object from 'C:\\Python\\lib\\importlib\\__pycache__\\machinery.cpython-37.pyc'
import 'importlib.machinery' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA8F5908>
import 'importlib.abc' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA8F12C8>
# C:\Python\lib\__pycache__\contextlib.cpython-37.pyc matches C:\Python\lib\contextlib.py
# code object from 'C:\\Python\\lib\\__pycache__\\contextlib.cpython-37.pyc'
# C:\Python\lib\collections\__pycache__\__init__.cpython-37.pyc matches C:\Python\lib\collections\__init__.py
# code object from 'C:\\Python\\lib\\collections\\__pycache__\\__init__.cpython-37.pyc'
# C:\Python\lib\__pycache__\operator.cpython-37.pyc matches C:\Python\lib\operator.py
# code object from 'C:\\Python\\lib\\__pycache__\\operator.cpython-37.pyc'
import '_operator' # <class '_frozen_importlib.BuiltinImporter'>
import 'operator' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDAA2CB48>
# C:\Python\lib\__pycache__\keyword.cpython-37.pyc matches C:\Python\lib\keyword.py
# code object from 'C:\\Python\\lib\\__pycache__\\keyword.cpython-37.pyc'
import 'keyword' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDAA2FA88>
# C:\Python\lib\__pycache__\heapq.cpython-37.pyc matches C:\Python\lib\heapq.py
# code object from 'C:\\Python\\lib\\__pycache__\\heapq.cpython-37.pyc'
import '_heapq' # <class '_frozen_importlib.BuiltinImporter'>
import 'heapq' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDAA3C548>
import 'itertools' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Python\lib\__pycache__\reprlib.cpython-37.pyc matches C:\Python\lib\reprlib.py
# code object from 'C:\\Python\\lib\\__pycache__\\reprlib.cpython-37.pyc'
import 'reprlib' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDAA3F748>
import '_collections' # <class '_frozen_importlib.BuiltinImporter'>
import 'collections' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA90BA08>
# C:\Python\lib\__pycache__\functools.cpython-37.pyc matches C:\Python\lib\functools.py
# code object from 'C:\\Python\\lib\\__pycache__\\functools.cpython-37.pyc'
import '_functools' # <class '_frozen_importlib.BuiltinImporter'>
import 'functools' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDAA1F908>
import 'contextlib' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA8F50C8>
import 'importlib.util' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA8E4EC8>
# possible namespace for C:\Python\lib\site-packages\ruamel
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x0000029DDA75DC48>
Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>
>>>
```

**Comment by lovasoa** [comment]
Thank you for the full report ! I am going to fix this

The issue cannot be reproduced with all URLs. For instance, `https://artsandculture.google.com/asset/waterloo-bridge-claude-monet/DwE25c4VOCwboQ` doesn't work, but `https://artsandculture.google.com/asset/the-water-carrier-la-aguadora/UwE2fGsMlWHuMg` does.

**Comment by lovasoa** [comment]
I think this is the same bug as https://github.com/lovasoa/dezoomify/issues/330 which is related to the changed format of google arts pages. Changes were made in dezoomify and dezoomify-rs, but not here.
